### ISSUE TITLE
[Bug] Clicking the UI Info Suite in the settings when trying to remap a control softlocks the game

### ISSUE THREAD

**Issue by KLaurence** [cdaragorn/Ui-Info-Suite#32]
Procedure to softlock the game:
1. Open the Options tab of the settings
2. Scroll down; click set on any control
3. Click the "UI Info Mod Options" tab while "Press new key..." can be seen

**Comment by Moonwolf287** [comment]
Just saw that Options page does count towards pages but not tabs in the Game1.activeClickableMenu.
It might be a starting point to investigate, since all other tabs seem to be greyed out / disabled during key input.
![grafik](https://user-images.githubusercontent.com/1161223/70537650-179a7e80-1b61-11ea-952a-eca5abb45ad3.png)

**Comment by Zamiell** [comment]
This will now be tracked here: https://github.com/Annosz/UIInfoSuite2/issues/14

**Comment by KLaurence** [comment]
Was fixed according to [this comment](https://github.com/Annosz/UIInfoSuite2/issues/14#issuecomment-711347248).
